# Generated by Django 5.1.7 on 2025-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
