# Generated by Django 5.0.6 on 2024-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='final_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
