# Generated by Django 5.0.6 on 2024-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_applesystem_delete_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applesystem',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'Apple systems'},
        ),
        migrations.AlterField(
            model_name='applesystem',
            name='final_price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='applesystem',
            name='normal_price',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
