# Generated by Django 5.0.6 on 2024-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_applesystem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applesystem',
            name='final_price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='applesystem',
            name='normal_price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
