# Generated by Django 5.0.6 on 2024-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_applesystem_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopsandtablet',
            name='final_price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='laptopsandtablet',
            name='normal_price',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='normal_price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
