# Generated by Django 5.0.6 on 2024-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='applesystem',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='componentsandparts',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='computeraccessories',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='gaminglaptops',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='heelsandslippers',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='laptopsandtablet',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='shoesandslippers',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
        migrations.AddField(
            model_name='surveillancesystems',
            name='product_availability',
            field=models.CharField(choices=[('in store', 'in stock'), ('out of stock', 'out of store')], default='in stock', max_length=20),
        ),
    ]
