# Generated by Django 5.0.6 on 2024-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_category_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applesystem',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='componentsandparts',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='computeraccessories',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='gaminglaptops',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='heelsandslippers',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='laptopsandtablet',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoesandslippers',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveillancesystems',
            name='product_availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20),
        ),
    ]
