# Generated by Django 5.0.6 on 2024-08-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_orderitem_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='delivered',
            new_name='stutus',
        ),
    ]
