# Generated by Django 5.0.6 on 2024-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem_date_added_alter_orderitem_stutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='stutus',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Not Delivered', max_length=50),
        ),
    ]
