# Generated by Django 5.0.6 on 2024-08-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_orderitem_stutus_orderitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.orderitem')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.shippingaddress')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
