# Generated by Django 5.0.6 on 2024-08-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_options_alter_orderitem_options_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='shipping',
        ),
    ]
