# Generated by Django 5.0.6 on 2024-08-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_order_remove_payment_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
