# Generated by Django 5.0.6 on 2024-08-10 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_payment_order_item_payment_shipping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='shipping',
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(default='Ghana', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
