# Generated by Django 5.0.6 on 2024-08-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_payment_shipping_payment_address_payment_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
