# Generated by Django 5.0.6 on 2024-08-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Order Items'},
        ),
    ]
