# Generated by Django 5.0.6 on 2024-08-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_orderitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='client',
        ),
    ]
