# Generated by Django 5.0.6 on 2024-08-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_rename_user_order_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='client',
            new_name='user',
        ),
    ]
