# Generated by Django 5.0.6 on 2024-08-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(null=True, verbose_name='date ordered'),
        ),
    ]
