# Generated by Django 5.0.6 on 2024-10-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_shippingfee_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingfee',
            old_name='region',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
