# Generated by Django 5.0.6 on 2024-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_rename_region_shippingfee_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
