# Generated by Django 5.0.6 on 2024-11-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_rename_country_shippingfee_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
