# Generated by Django 5.0.6 on 2024-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_shippingfee_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
